---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: KaleidOS
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: akmods
    nvidia-driver: nvidia-open
    install:
      - xone
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
      files:
        - https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        - vscode.repo
        - 1password.repo
        - https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
      keys:
        - https://packages.microsoft.com/keys/microsoft.asc
        - https://download.sublimetext.com/sublimehq-rpm-pub.gpg
        - https://downloads.1password.com/linux/keys/1password.asc
    install:
      packages:
        - greetd
        - tuigreet
        - dialog
        - acl
        - code
        - sublime-text
        - tailscale
        - xeyes
        - https://bitwarden.com/download/?app=desktop&platform=linux&variant=rpm
        - gnome-themes-extra
        - 1password
        # - power-profiles-daemon 
        # - micro
        # - starship
    group-install:
      packages:
        - kde-desktop-environment
        # - xfce-desktop-environment
        # - pantheon-desktop-environment
    # remove:
    #   packages:
    #     # example: removing firefox (in favor of the flatpak)
    #     # "firefox" is the main package, "firefox-langpacks" is a dependency
  
  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode 

  - type: systemd
# this example disables automatic flatpak updates and enables a custom service unit for all users
    system:
      enabled:
        - greetd.service
        # - power-profiles-daemon.service
        - de-firstboot.service
        - tailscaled
      disabled:
        - gdm.service
        - sddm.service
        # - lightdm.service
        - display-manager.service
      masked:
        - gdm.service
        - sddm.service
        # - lightdm.service
        - display-manager.service
        - getty@tty1.service
    user:
      disabled:
        - org.gnome.SettingsDaemon.Power.service
        - powerdevil.service
        # - xfce4-power-manager.service
        # - io.elementary.settings-daemon.power.service
      masked:
        - org.gnome.SettingsDaemon.Power.service
        - powerdevil.service
        # - xfce4-power-manager.service
        # - io.elementary.settings-daemon.power.service

  # - type: default-flatpaks
  #   configurations:
  #     - notify: true # Send notification after install/uninstall is finished (true/false)
  #       scope: system
  #       # If no repo information is specified, Flathub will be used by default
  #       install: # system flatpaks we want all users to have and not remove
  #         - org.mozilla.firefox
  #         - org.gnome.Loupe
  #     - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
